### ISSUE TITLE
Crash when starting....

### ISSUE THREAD

**Issue by MikeTheWatchGuy** [allenfrostline/Poker#1]
When running poker_gui.py, the file I assume you run to start playing, it crashes with this traceback:

```
C:\Python\Anaconda3\python.exe C:/Python/PycharmProjects/GitHub/Poker/poker_gui.py
Traceback (most recent call last):
  File "C:/Python/PycharmProjects/GitHub/Poker/poker_gui.py", line 523, in <module>
    g = Game(n_players=9, buy_in=10, seed='random')
  File "C:/Python/PycharmProjects/GitHub/Poker/poker_gui.py", line 42, in __init__
    self.__welcome()
  File "C:/Python/PycharmProjects/GitHub/Poker/poker_gui.py", line 68, in __welcome
    with absOpen('hv.json', 'r') as f: self.__hv = json.load(f)
  File "C:\Python\PycharmProjects\GitHub\Poker\misc.py", line 331, in absOpen
    return open(absPath(name), mode=mode, buffering=1)
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Python\\PycharmProjects\\GitHub\\Poker\\hv.json'
```

**Comment by allenfrostline** [comment]
Ha... Sorry, I forgot that I ignored the hand value table file from the repo. The file is rather large and I don't want to include it here (as you can generate it in fact, using the evaluation methods). Please go to this [link](https://drive.google.com/open?id=1orbU6vtaKGufg9y39ABTqgxbMVJ8e47k) to download the missing file. Tell me if there's anything wrong on Windows. Never tested on Win yet.

**Comment by allenfrostline** [comment]
`hv.json` is now in the repo.

**Comment by MikeTheWatchGuy** [comment]
got it!  Starts up ok now!
